# Generated by Django 5.1 on 2024-08-13 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0001_initial'),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractionhistory',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.choice'),
        ),
        migrations.AlterField(
            model_name='useractionhistory',
            name='action',
            field=models.CharField(choices=[('Vote', 'Vote'), ('Login', 'Login'), ('Logout', 'Logout')], max_length=20),
        ),
    ]
