# Generated by Django 5.1 on 2024-08-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0002_useractionhistory_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractionhistory',
            name='action',
            field=models.CharField(choices=[('Vote', 'Vote')], max_length=20),
        ),
    ]
